#!/bin/bash

# sudo apt install extra-cmake-modules
# sudo apt install plasma-framework-dev

# https://stackoverflow.com/questions/911168/how-to-detect-if-my-shell-script-is-running-through-a-pipe
if [ -t 1 ]; then
	sudoCmd="sudo"
else
	sudoCmd="kdesudo"
fi


buildDir="out"

rm -r $buildDir
(mkdir $buildDir && cd $buildDir \
	&& cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DKDE_INSTALL_LIBDIR=lib -DKDE_INSTALL_USE_QT_SYS_PATHS=ON \
	&& make \
	&& $sudoCmd make install \
)
